### ISSUE TITLE
error with use minify-js

### ISSUE THREAD

**Issue by ehlxr** [theme-next/hexo-filter-optimize#3]
![image](https://user-images.githubusercontent.com/11313370/35616876-84cd839c-06b1-11e8-998b-3eed9072caaf.png)

**Comment by tsanie** [comment]
css file with `@import` would not be bundled correctly, try to add those css file into the `filter_optimize.css.excludes` first and see if there is still a problem.

**Comment by tsanie** [comment]
The minifier would try to parse the css content, and I find that just only enable the minifier plugin will also lead that problem. (because there is a line `@import url('font-embedded.css');` in the `needsharebutton.css`)

![image](https://user-images.githubusercontent.com/980449/35655893-3a5ea2ae-072f-11e8-818e-f09164bdbdba.png)
Please add the `needsharebutton.css` into the exclude of minify-css first, like:
```yml
  clean_css:
    enable: true
    exclude:
      - '**/needsharebutton.css'
      - '**/*.min.css'
```

But in that way, you may also need to add them into the excludes of `hexo-filter-optimize` too.
Or you can follow the steps in https://github.com/theme-next/hexo-filter-optimize/issues/4#issuecomment-361941409 to resolve it manually.

**Comment by ehlxr** [comment]
thx, i resolved the problem by the way https://github.com/theme-next/hexo-filter-optimize/issues/4#issuecomment-361941409
